name: Secrets Scan

on:
  push:
    branches:
      - gh-pages

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Scan built docs for leaked secrets
        uses: docker://zricethezav/gitleaks:latest
        with:
          args: detect --no-git --source . -v
